# Generated by Django 5.2.4 on 2025-08-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_habit_habitrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='tracking_type',
            field=models.CharField(choices=[('bool', 'Checkbox (Yes/No)'), ('int', 'Integer (Number)')], default='bool', max_length=8),
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
